# https://docs.github.com/en/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2

updates:
    -   commit-message:
            include: "scope"
            prefix: "composer"
        directory: "/"
        open-pull-requests-limit: 1
        package-ecosystem: "composer"
        schedule:
            interval: "daily"
        versioning-strategy: "widen"

    -   commit-message:
            include: "scope"
            prefix: "github-actions"
        directory: "/"
        open-pull-requests-limit: 1
        package-ecosystem: "github-actions"
        schedule:
            interval: "daily"
